name: poetryRNN
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.10
  
  # Core ML Stack
  - pytorch::pytorch>=2.0.0
  - pytorch::torchvision  
  - pytorch::torchaudio
  - numpy>=1.24.0
  - scipy>=1.10.0
  - matplotlib>=3.6.0
  - seaborn>=0.12.0
  
  # Jupyter Environment
  - jupyter>=1.0.0
  - jupyterlab>=4.0.0
  - ipython>=8.0.0
  - ipywidgets>=8.0.0
  
  # Text Processing & NLP
  - pandas>=2.0.0
  - scikit-learn>=1.3.0
  - nltk>=3.8.0
  - spacy>=3.6.0
  
  # Development & Utilities
  - tqdm>=4.65.0
  - pytest>=7.0.0
  - black  # code formatting
  - isort  # import sorting
  
  # Visualization & Analysis
  - plotly>=5.0.0
  - umap-learn  # for dimensionality visualization
  
  # Pip dependencies (not available via conda)
  - pip
  - pip:
    # HuggingFace ecosystem
    - transformers>=4.30.0
    - datasets>=2.10.0
    - tokenizers>=0.13.0
    
    # Training monitoring
    - tensorboard>=2.13.0
    - wandb  # weights & biases (optional)
    
    # Additional NLP utilities  
    - spacy-transformers  # transformer models for spacy
    - gensim>=4.3.0  # word embeddings utilities
    
    # Text similarity and evaluation
    - sentence-transformers>=2.2.0
    - sacrebleu>=2.3.0  # BLEU score implementation
    
    # Additional scientific computing
    - einops>=0.6.0  # tensor operations
    - torchinfo>=1.8.0  # model architecture summary